import type { MachineType, MachineTypeKPIs } from "../types/machineType.types";

export const DUMMY_MACHINE_TYPES: MachineType[] = [
  {
    id: "mt-001",
    typeCode: "SN-01",
    typeName: "Single Needle Lockstitch",
    manufacturer: "Juki",
    description: "Standard single needle machine for general seaming.",
    capacity: 3500,
    powerRating: "220V, 400W",
    speed: "4500 RPM",
    supportedOperations: ["Straight Seam", "Top Stitching", "Edge Stitching"],
    maintenanceIntervalDays: 30,
    status: "active",
    totalMachines: 45,
    averageEfficiency: 92,
  },
  {
    id: "mt-002",
    typeCode: "OL-04",
    typeName: "4-Thread Overlock",
    manufacturer: "Pegasus",
    description: "Overlock machine for edge finishing and seaming knits.",
    capacity: 4000,
    powerRating: "220V, 550W",
    speed: "6000 RPM",
    supportedOperations: ["Overlocking", "Edge Finishing"],
    maintenanceIntervalDays: 45,
    status: "active",
    totalMachines: 32,
    averageEfficiency: 88,
  },
  {
    id: "mt-003",
    typeCode: "FL-03",
    typeName: "Flatlock Machine",
    manufacturer: "Kansai Special",
    description: "Coverstitch machine for hems and decorative seams.",
    capacity: 2800,
    powerRating: "220V, 600W",
    speed: "4000 RPM",
    supportedOperations: ["Hemming", "Coverstitching"],
    maintenanceIntervalDays: 60,
    status: "active",
    totalMachines: 18,
    averageEfficiency: 85,
  },
  {
    id: "mt-004",
    typeCode: "BH-01",
    typeName: "Button Hole Machine",
    manufacturer: "Brother",
    description: "Automated button hole sewing machine.",
    capacity: 1500,
    powerRating: "220V, 500W",
    speed: "3600 RPM",
    supportedOperations: ["Button Holing"],
    maintenanceIntervalDays: 20,
    status: "maintenance",
    totalMachines: 8,
    averageEfficiency: 78,
  },
  {
    id: "mt-005",
    typeCode: "BT-02",
    typeName: "Button Attach Machine",
    manufacturer: "Juki",
    description: "Machine for automatically attaching buttons.",
    capacity: 2000,
    powerRating: "220V, 400W",
    speed: "2700 RPM",
    supportedOperations: ["Button Attaching"],
    maintenanceIntervalDays: 30,
    status: "active",
    totalMachines: 12,
    averageEfficiency: 90,
  }
];

export const DUMMY_KPIS: MachineTypeKPIs = {
  totalTypes: 12,
  totalMachines: 154,
  activeTypes: 10,
  maintenanceDue: 3,
  supportedOperations: 24,
  averageUtilization: 86.5,
};
